version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
  server:
    container_name: server
    image: space
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/test